### ISSUE TITLE
en-dash in page range is treated as text

### ISSUE THREAD

**Issue by chreliot** [maieul/biblatex-true-citepages-omit#1]
This package fails to omit the page numbers when a page range is invoked using the (typographically-preferred) en-dash. That is, the package succeeds with

`\autocite[92-94]{Darwin1859}`

but fails with

`\autocite[92–94]{Darwin1859}`

I know there is the easy work-around of typing the en-dash as “`--`" in both pdfTeX and XeTeX. But, using unicode characters in XeTeX, I am in the habit of typing en-dashes.

This may not be worth your time to fix. But it might help avoid confusion, and I would welcome it!

**Comment by maieul** [comment]
your two example are identifcal. Please provides a full MWE

**Comment by chreliot** [comment]
Actually, they aren't identical — the first uses a hyphen, and the second uses an en-dash. To illustrate, here are MWEs. This first example works correctly with a hyphen:

```
\documentclass[nobib]{tufte-handout}

\usepackage{fontspec,xunicode}
\setromanfont[Mapping=tex-text]{Adobe Caslon Pro}
\setsansfont[Scale=MatchLowercase,Mapping=tex-text]{Helvetica}

\usepackage[
  style=verbose,
  autocite=footnote,
  citepages=omit,
  backend=biber
]{biblatex}
\usepackage{biblatex-true-citepages-omit}
\addbibresource{biblatex-examples.bib}

\begin{document}

The cite-pages-omit package will succeed at removing book pages in this example\autocite[93-94]{springer} but will display a typographically less-desirable hyphen for the page range.

\printbibliography 

\end{document}
```

That produces: 
![screen shot 2016-09-26 at 9 49 26 am](https://cloud.githubusercontent.com/assets/6901739/18836599/b56a3f5c-83ce-11e6-8eef-dabae0c7f157.png)

Here is an MWE in which the package does not work, because the en-dash is used:

```
\documentclass[nobib]{tufte-handout}

\usepackage{fontspec,xunicode}
\setromanfont[Mapping=tex-text]{Adobe Caslon Pro}
\setsansfont[Scale=MatchLowercase,Mapping=tex-text]{Helvetica}

\usepackage[
  style=verbose,
  autocite=footnote,
  citepages=omit,
  backend=biber
]{biblatex}
\usepackage{biblatex-true-citepages-omit}
\addbibresource{biblatex-examples.bib}

\begin{document}

It will fail at removing book pages in this example, which uses a typographically-preferable en-dash for the page range.\autocite[93–94]{springer}

\printbibliography 

\end{document}
```

That produces:

![screen shot 2016-09-26 at 9 52 32 am](https://cloud.githubusercontent.com/assets/6901739/18836659/feb36742-83ce-11e6-80b6-cb9d0deaf7e7.png)

Thanks!

**Comment by maieul** [comment]
please also provides the .bib file

**Comment by chreliot** [comment]
I think that .bib file is distributed as part of the `biblatex` package, but if not, here is a link: http://tug.ctan.org/macros/latex2e/exptl/biblatex/doc/examples/biblatex-examples.bib

**Comment by maieul** [comment]
ok, I didn't see you're were asking for example.

please, next time provides me directly all the information to use your MWE.

**Comment by chreliot** [comment]
Okay, I'm sorry — I believed it would work with no additional information!

**Comment by maieul** [comment]
yes, it would, be, by experience, I never try to run file provides by user if I have not all the information. Because make test is time consuming, and my time is precious.

**Comment by maieul** [comment]
I have looked on your example.
It is not related to this package, which concerns only the case you use \pno at the beginning of an optional argument.
So your problem concern directly biblatex.

Your problem is that your use a utf8 en-dash (`�`)  and not a LaTeX en-dash (`--`).

If you want to use an utf8 en-dash, I think you should use `\DeclareRangeCommands`, but 
`\DeclareRangeCommands*{�}` is not working. It is a biblatex problem, not a problem of my package.
